### ISSUE TITLE
Choose and upload a LISCENSE

### ISSUE THREAD

**Issue by eliasbenb** [CMPINF-0010-Version-Control/hello-world#1]

**Comment by eliasbenb** [comment]
@Dyoung778 for this week's lab we have to create 3 new files

- README.md
- LISCENSE
- CODE-OF-CONDUCT.md

I already did the README and CODE-OF-CONDUCT. All that's left for you to do is choose the LISCENSE and write about why you chose it in the README.

I won't be at the lab this Friday, so if you need anything from me, we can communicate through this issue.

**Comment by eliasbenb** [comment]
@Dyoung778 I saw that you uploaded the license. I fixed some issues and added info about it to the README. Please go over it and tell me if I'm missing anything.
I'm also going to submit our assignment on canvas now.

**Comment by Dyoung778** [comment]
@eliasbenb It all looks good to me.
